name: Invincible
version: '1.0-SNAPSHOT'
main: git.snowk.invincible.Invincible
authors: [snowk]
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - HolographicDisplays
  - DecentHolograms